### PR TITLE
feat(rule): import react rule

### PR DESCRIPTION
**Pull request by cyberhck**

### CODE REVIEW

**Comment by cyberhck** [comment]
I couldn't figure out how to do the testing, and it's too late to do the options correctly, can you take over? thanks

**Comment by paibamboo** [comment]
Hey I just saw this, why are we using `walk` here?

**Comment by cyberhck** [comment]
we should be using `walk` instead of class with `visitSomething()` because walk is way faster, tslint people recommended this way. they were in the verge of converting, and now they've deprecated, you can also start writing in new way I'm not sure what way it is.

it's too late as in, I did a bit of work, it was evening and I didn't have any time left.

**Pull request closed without merging**
